version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8010:80"

  backend:
    build: ./backend
    ports:
      - "8020:80"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      